sudo: required

os:
- osx
- linux

language: node_js
node_js:
- '6'

before_install:
- npm install -g gulp
- npm install

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

script:
- npm run travis
